#' Random Numbers Data Set
#'
#' Random numbers from the output of sample(100)
#'
#' @docType data
#'
#' @usage data(randomNum)
#'
#' @format Vector of 100 numbers
#'
#' @keywords datasets
#'
#' @references generated by following directions of: http://kbroman.org/pkg_primer/pages/data.html
#'
#' @source sample(1000)
#'
#' @examples
"randomNum"
